// Validates contrast of every token pair and generates src/design/tokens.css
import { writeFileSync } from 'node:fs'
import { tokens as T } from '../src/design/tokens.mjs'

const lin = (c) => { c /= 255; return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4 }
const L = (h) => { const [r, g, b] = [1, 3, 5].map((i) => lin(parseInt(h.slice(i, i + 2), 16))); return 0.2126 * r + 0.7152 * g + 0.0722 * b }
const ratio = (a, b) => { const x = L(a), y = L(b); return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05) }

const pairs = (t) => [
  ['ink / bg', t.ink, t.bg, 4.5], ['ink / surface', t.ink, t.surface, 4.5], ['ink / raised', t.ink, t.raised, 4.5],
  ['ink2 / bg', t.ink2, t.bg, 4.5], ['ink2 / surface', t.ink2, t.surface, 4.5], ['ink2 / raised', t.ink2, t.raised, 4.5],
  ['ink3 / bg', t.ink3, t.bg, 4.5], ['ink3 / surface', t.ink3, t.surface, 4.5],
  ['accent / bg', t.accent, t.bg, 4.5], ['accent / surface', t.accent, t.surface, 4.5], ['accent / raised', t.accent, t.raised, 4.5],
  ['onAction / action', t.onAction, t.action, 4.5], ['onAction / actionHover', t.onAction, t.actionHover, 4.5],
  ['ok / okBg', t.ok, t.okBg, 4.5], ['late / lateBg', t.late, t.lateBg, 4.5], ['warn / warnBg', t.warn, t.warnBg, 4.5],
  ['ok / surface', t.ok, t.surface, 4.5], ['late / surface', t.late, t.surface, 4.5],
  ['lineStrong / bg (UI 3:1)', t.lineStrong, t.bg, 3], ['lineStrong / surface (UI 3:1)', t.lineStrong, t.surface, 3],
]

let fail = 0
for (const th of ['dark', 'light']) {
  for (const [n, f, b, min] of pairs(T[th])) {
    const r = ratio(f, b)
    if (r < min) { fail++; console.log(`FAIL ${th.padEnd(5)} ${n.padEnd(30)} ${r.toFixed(2)} < ${min}`) }
  }
}
const kebab = (k) => k.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase())
const block = (t) => Object.entries(t).map(([k, v]) => `  --${kebab(k)}: ${v};`).join('\n')

const css = `/* GENERATED by scripts/design-tokens.mjs from src/design/tokens.mjs. Do not edit. */
:root, [data-theme='dark'] {
  color-scheme: dark;
${block(T.dark)}
}
[data-theme='light'] {
  color-scheme: light;
${block(T.light)}
}
`
writeFileSync(new URL('../src/design/tokens.css', import.meta.url), css)
console.log(fail ? `${fail} contrast pair(s) FAIL` : 'contrast: all pairs pass AA, tokens.css written')
process.exit(fail ? 1 : 0)
